-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 18:09:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ISPS_POSTS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ISPS_POSTS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ISPS_POSTS` DEFAULT CHARACTER SET utf8 ;
USE `ISPS_POSTS` ;

-- -----------------------------------------------------
-- Table `ISPS_POSTS`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPS_POSTS`.`posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `post_name` VARCHAR(45) NULL,
  `views` INT NULL,
  `post_type` VARCHAR(45) NULL,
  `likes_number` INT NULL,
  `comments_number` INT NULL,
  `forward_number` INT NULL,
  `post_time` VARCHAR(45) NULL,
  `account_id` INT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_posts_id_idx` (`post_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISPS_POSTS`.`post_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPS_POSTS`.`post_details` (
  `post_id` INT NOT NULL,
  `details` VARCHAR(21842) NULL,
  PRIMARY KEY (`post_id`),
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC) VISIBLE,
  INDEX `fk_pd_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_details_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `ISPS_POSTS`.`posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISPS_POSTS`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPS_POSTS`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(225) NULL,
  `likes_number` INT NULL,
  `comment_time` VARCHAR(45) NULL,
  `post_id` INT NOT NULL,
  `account_id` INT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comments_posts1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `ISPS_POSTS`.`posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '评论';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
