-- MySQL Script generated by MySQL Workbench
-- Fri Aug 11 19:35:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema permission
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema permission
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `permission` DEFAULT CHARACTER SET utf8 ;
USE `permission` ;

-- -----------------------------------------------------
-- Table `permission`.`system_administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permission`.`system_administrators` (
  `account_id` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permission`.`moderators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permission`.`moderators` (
  `account_id` INT NOT NULL,
  `plates_id` VARCHAR(21842) NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '版主';


-- -----------------------------------------------------
-- Table `permission`.`manage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permission`.`manage` (
  `plate_id` INT NOT NULL,
  `account_id` VARCHAR(21842) NULL,
  PRIMARY KEY (`plate_id`),
  UNIQUE INDEX `plate_id_UNIQUE` (`plate_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '管理员';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
