-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 18:07:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ISPS_users
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ISPS_users
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ISPS_users` ;
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------
USE `ISPS_users` ;

-- -----------------------------------------------------
-- Table `ISPS_users`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPS_users`.`accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  UNIQUE INDEX `account_UNIQUE` (`account` ASC) INVISIBLE,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISPS_users`.`information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPS_users`.`information` (
  `account_id` INT NOT NULL,
  `account_name` VARCHAR(45) NULL,
  `age` INT NULL,
  `sex` VARCHAR(45) NULL,
  `posts_number` INT NULL,
  `posts_id` VARCHAR(16120) NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_in_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_information_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `ISPS_users`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISPS_users`.`concern_people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPS_users`.`concern_people` (
  `account_id` INT NOT NULL,
  `concern_people_number` INT NULL,
  `concern_people_id` VARCHAR(16380) NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_cp_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_concern_people_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `ISPS_users`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISPS_users`.`fans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPS_users`.`fans` (
  `account_id` INT NOT NULL,
  `fans_number` INT NULL,
  `fans_id` VARCHAR(16380) NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_fs_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_fans_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `ISPS_users`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISPS_users`.`concern_plates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPS_users`.`concern_plates` (
  `account_id` INT NOT NULL,
  `concern_plates_number` INT NULL,
  `concern_plates_id` VARCHAR(16380) NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_cpl_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_concern_plates_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `ISPS_users`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
